### ISSUE TITLE
Release: Version release mismatch with master branch

### ISSUE THREAD

**Issue by istatkovs** [alexsergivan/transliterator#4]
I've noticed that version 1.0.0 is tagged for an old commit: [7d9e0fc] (4 years ago)
While the master branch is advanced with more changes: [ea2215d] (2 years ago)

Doing so would allow easier imports where we don;t need to specify the hash for the latest version in go.mod.

Could you be so kind to put out a new release?

Thanks!

**Comment by alexsergivan** [comment]
Hey! Thanks for pointing out it.
Just pushed a v1.0.1
